Repository ianshulx/React-projects-for-beginners, pull requests merged in 2024-10, with the labels that each got.

#88 Add markdown previewer
  Markdown-Previewer/.gitignore
  Markdown-Previewer/README.md
  Markdown-Previewer/eslint.config.js
  Markdown-Previewer/index.html
  Markdown-Previewer/package-lock.json
  Markdown-Previewer/package.json
  Markdown-Previewer/postcss.config.js
  Markdown-Previewer/public/vite.svg
  Markdown-Previewer/src/App.tsx
  Markdown-Previewer/src/assets/react.svg
  Markdown-Previewer/src/index.css
  Markdown-Previewer/src/main.tsx
  Markdown-Previewer/src/vite-env.d.ts
  Markdown-Previewer/tailwind.config.js
  Markdown-Previewer/tsconfig.app.json
  Markdown-Previewer/tsconfig.app.tsbuildinfo
  Markdown-Previewer/tsconfig.json
  Markdown-Previewer/tsconfig.node.json
  Markdown-Previewer/tsconfig.node.tsbuildinfo
  Markdown-Previewer/vite.config.ts
  index.html
  package-lock.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#89 Add IP Info Project
  ip-info/.eslintrc.cjs
  ip-info/.gitignore
  ip-info/README.md
  ip-info/index.html
  ip-info/package-lock.json
  ip-info/package.json
  ip-info/public/vite.svg
  ip-info/src/App.css
  ip-info/src/App.jsx
  ip-info/src/index.css
  ip-info/src/main.jsx
  ip-info/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#92 feat: react file size converter
  react-file-size-converter/README.md
  react-file-size-converter/eslint.config.js
  react-file-size-converter/index.html
  react-file-size-converter/package-lock.json
  react-file-size-converter/package.json
  react-file-size-converter/postcss.config.js
  react-file-size-converter/src/App.tsx
  react-file-size-converter/src/index.css
  react-file-size-converter/src/main.tsx
  react-file-size-converter/src/vite-env.d.ts
  react-file-size-converter/tailwind.config.js
  react-file-size-converter/tsconfig.app.json
  react-file-size-converter/tsconfig.json
  react-file-size-converter/tsconfig.node.json
  react-file-size-converter/vite.config.ts
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#100 Added a task manager React app
  .DS_Store
  Task-Manager-App/.DS_Store
  Task-Manager-App/README.md
  Task-Manager-App/package.json
  Task-Manager-App/public/delete.png
  Task-Manager-App/public/edit.png
  Task-Manager-App/public/favicon.ico
  Task-Manager-App/public/high-priority.png
  Task-Manager-App/public/index.html
  Task-Manager-App/public/manifest.json
  Task-Manager-App/public/priority.png
  Task-Manager-App/public/robots.txt
  Task-Manager-App/public/tasklear.png
  Task-Manager-App/src/.DS_Store
  Task-Manager-App/src/App.css
  Task-Manager-App/src/App.js
  Task-Manager-App/src/App.test.js
  Task-Manager-App/src/components/Task.js
  Task-Manager-App/src/components/TaskList.js
  Task-Manager-App/src/index.css
  Task-Manager-App/src/index.js
  Task-Manager-App/src/logo.svg
  Task-Manager-App/src/reportWebVitals.js
  Task-Manager-App/src/setupTests.js
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#105 Kanban: Drag and Drop Board
  draganddrop-board/.gitignore
  draganddrop-board/README.md
  draganddrop-board/eslint.config.js
  draganddrop-board/index.html
  draganddrop-board/package-lock.json
  draganddrop-board/package.json
  draganddrop-board/postcss.config.js
  draganddrop-board/public/vite.svg
  draganddrop-board/src/App.css
  draganddrop-board/src/App.tsx
  draganddrop-board/src/assets/react.svg
  draganddrop-board/src/components/Column.tsx
  draganddrop-board/src/components/Task.tsx
  draganddrop-board/src/index.css
  draganddrop-board/src/main.tsx
  draganddrop-board/src/types/columnTypes.tsx
  draganddrop-board/src/types/taskTypes.tsx
  draganddrop-board/src/vite-env.d.ts
  draganddrop-board/tailwind.config.js
  draganddrop-board/tsconfig.app.json
  draganddrop-board/tsconfig.json
  draganddrop-board/tsconfig.node.json
  draganddrop-board/vite.config.ts
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#107 Kanban board added to Project.js
  assets/drag-and-drop.png
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#108 Added The logo At index.html
  assets/ChatGram.png
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#114 made changes for proper redirect to git repos
  index.css
  projects.js
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024, UI

#122 #115: Updated project.js
  assets/Bportfolio.png
  assets/Taskmanager.png
  assets/blood_bank.png
  assets/file_size.png
  assets/form.png
  assets/ip_info.png
  assets/medicine_delivery.png
  assets/memeG.png
  assets/reactPortfolio.png
  assets/resumeBuilder.png
  assets/wallet.png
  package-lock.json
  projects.js
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#125 Add:React-password-manager
  React-password-manager/passop-mongo/.gitignore
  React-password-manager/passop-mongo/README.md
  React-password-manager/passop-mongo/backend/.env
  React-password-manager/passop-mongo/backend/package-lock.json
  React-password-manager/passop-mongo/backend/package.json
  React-password-manager/passop-mongo/backend/server.js
  React-password-manager/passop-mongo/eslint.config.js
  React-password-manager/passop-mongo/index.html
  React-password-manager/passop-mongo/package-lock.json
  React-password-manager/passop-mongo/package.json
  React-password-manager/passop-mongo/postcss.config.js
  React-password-manager/passop-mongo/public/favicons.png
  React-password-manager/passop-mongo/public/icons/eye.png
  React-password-manager/passop-mongo/public/icons/eyecross.png
  React-password-manager/passop-mongo/public/icons/github.svg
  React-password-manager/passop-mongo/public/icons/heart.png
  React-password-manager/passop-mongo/public/vite.svg
  React-password-manager/passop-mongo/src/App.css
  React-password-manager/passop-mongo/src/App.jsx
  React-password-manager/passop-mongo/src/assets/react.svg
  React-password-manager/passop-mongo/src/components/Footer.jsx
  React-password-manager/passop-mongo/src/components/Manager.jsx
  React-password-manager/passop-mongo/src/components/Navbar.jsx
  React-password-manager/passop-mongo/src/index.css
  React-password-manager/passop-mongo/src/main.jsx
  React-password-manager/passop-mongo/tailwind.config.js
  React-password-manager/passop-mongo/vite.config.js
  React-password-manager/passop/.gitignore
  React-password-manager/passop/README.md
  React-password-manager/passop/eslint.config.js
  React-password-manager/passop/index.html
  React-password-manager/passop/package-lock.json
  React-password-manager/passop/package.json
  React-password-manager/passop/postcss.config.js
  React-password-manager/passop/public/favicons.png
  React-password-manager/passop/public/icons/eye.png
  React-password-manager/passop/public/icons/eyecross.png
  React-password-manager/passop/public/icons/github.svg
  React-password-manager/passop/public/icons/heart.png
  React-password-manager/passop/public/vite.svg
  React-password-manager/passop/src/App.css
  React-password-manager/passop/src/App.jsx
  React-password-manager/passop/src/assets/react.svg
  React-password-manager/passop/src/components/Footer.jsx
  React-password-manager/passop/src/components/Manager.jsx
  React-password-manager/passop/src/components/Navbar.jsx
  React-password-manager/passop/src/index.css
  React-password-manager/passop/src/main.jsx
  React-password-manager/passop/tailwind.config.js
  React-password-manager/passop/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#124 Added Photoshop-Clone
  Photoshop-Clone/.gitignore
  Photoshop-Clone/README.md
  Photoshop-Clone/eslint.config.js
  Photoshop-Clone/index.html
  Photoshop-Clone/package-lock.json
  Photoshop-Clone/package.json
  Photoshop-Clone/public/vite.svg
  Photoshop-Clone/src/App.css
  Photoshop-Clone/src/App.jsx
  Photoshop-Clone/src/SidebarItem.jsx
  Photoshop-Clone/src/Slider.jsx
  Photoshop-Clone/src/assets/react.svg
  Photoshop-Clone/src/main.jsx
  Photoshop-Clone/vite.config.js
  package-lock.json
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#127 Listed the project in project.js
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#129 Added Credit-Card Validator
  Credit-Card-Validator/.gitignore
  Credit-Card-Validator/README.md
  Credit-Card-Validator/eslint.config.js
  Credit-Card-Validator/index.html
  Credit-Card-Validator/package-lock.json
  Credit-Card-Validator/package.json
  Credit-Card-Validator/src/App.css
  Credit-Card-Validator/src/App.jsx
  Credit-Card-Validator/src/assets/react.svg
  Credit-Card-Validator/src/main.jsx
  Credit-Card-Validator/vite.config.js
  assets/cc-validator.png
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#131 Added Typing-speed-tester
  Typing-test/.gitignore
  Typing-test/README.md
  Typing-test/eslint.config.js
  Typing-test/index.html
  Typing-test/package-lock.json
  Typing-test/package.json
  Typing-test/src/App.css
  Typing-test/src/App.jsx
  Typing-test/src/main.jsx
  Typing-test/vite.config.js
  assets/typing.png
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024, UI

#135 NFT MARKETPLACE (HACKTOBER ISSUE NOW CLOSED PLEASE REOPEN)
  .gitignore
  nft-marketplace/.gitignore
  nft-marketplace/README.md
  nft-marketplace/backend/TezosService.js
  nft-marketplace/backend/ethereumService.js
  nft-marketplace/backend/index.js
  nft-marketplace/backend/package-lock.json
  nft-marketplace/backend/package.json
  nft-marketplace/config-overrides.js
  nft-marketplace/package-lock.json
  nft-marketplace/package.json
  nft-marketplace/postcss.config.js
  nft-marketplace/public/favicon.ico
  nft-marketplace/public/index.html
  nft-marketplace/public/logo192.png
  nft-marketplace/public/logo512.png
  nft-marketplace/public/manifest.json
  nft-marketplace/public/robots.txt
  nft-marketplace/src/App.css
  nft-marketplace/src/App.js
  nft-marketplace/src/App.test.js
  nft-marketplace/src/AppLayout.js
  nft-marketplace/src/components/ColorModeSwitcher.tsx
  nft-marketplace/src/components/CombinedInteractions.tsx
  nft-marketplace/src/components/EthereumInteraction.js
  nft-marketplace/src/components/IPFSUpload.js
  nft-marketplace/src/components/NFTCard.js
  nft-marketplace/src/components/NFTList.js
  nft-marketplace/src/components/TezosInteraction.js
  nft-marketplace/src/components/UIComponents.js
  nft-marketplace/src/components/getComponents.js
  nft-marketplace/src/components/nftService.js
  nft-marketplace/src/components/simple.json
  nft-marketplace/src/components/token.json
  nft-marketplace/src/components/ui/badge.js
  nft-marketplace/src/components/ui/button.js
  nft-marketplace/src/components/ui/card.js
  nft-marketplace/src/components/ui/input.js
  nft-marketplace/src/components/ui/label.js
  nft-marketplace/src/components/ui/tabs.js
  nft-marketplace/src/components/ui/tooltip.js
  nft-marketplace/src/exampleIMG/nft1.jpg
  nft-marketplace/src/index.css
  nft-marketplace/src/index.js
  nft-marketplace/src/logo.svg
  nft-marketplace/src/pages/Marketplace.js
  nft-marketplace/src/pages/MyCollection.js
  nft-marketplace/src/pages/home.js
  nft-marketplace/src/reportWebVitals.js
  nft-marketplace/src/services/ethereumService.js
  nft-marketplace/src/services/tezosService.js
  nft-marketplace/src/setupTests.js
  nft-marketplace/src/styles.js
  nft-marketplace/src/styles/globals.css
  nft-marketplace/src/web3Provider.js
  nft-marketplace/src/webpack.config.js
  nft-marketplace/tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#137 FunFact Generator and HEX/RGB CONVERTER apps added
  Fun-Fact Generator/.gitignore
  Fun-Fact Generator/README.md
  Fun-Fact Generator/eslint.config.js
  Fun-Fact Generator/index.html
  Fun-Fact Generator/package-lock.json
  Fun-Fact Generator/package.json
  Fun-Fact Generator/postcss.config.js
  Fun-Fact Generator/public/vite.svg
  Fun-Fact Generator/src/App.jsx
  Fun-Fact Generator/src/assets/react.svg
  Fun-Fact Generator/src/components/FunFactGenerator.jsx
  Fun-Fact Generator/src/index.css
  Fun-Fact Generator/src/main.jsx
  Fun-Fact Generator/tailwind.config.js
  Fun-Fact Generator/vite.config.js
  HEX-RGB Converter/.gitignore
  HEX-RGB Converter/README.md
  HEX-RGB Converter/eslint.config.js
  HEX-RGB Converter/index.html
  HEX-RGB Converter/package-lock.json
  HEX-RGB Converter/package.json
  HEX-RGB Converter/postcss.config.js
  HEX-RGB Converter/public/vite.svg
  HEX-RGB Converter/src/App.jsx
  HEX-RGB Converter/src/assets/react.svg
  HEX-RGB Converter/src/components/ColorConverter.jsx
  HEX-RGB Converter/src/index.css
  HEX-RGB Converter/src/main.jsx
  HEX-RGB Converter/tailwind.config.js
  HEX-RGB Converter/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#138 learning streak tracker
  Learning Streak Tracker/App.css
  Learning Streak Tracker/App.js
  Learning Streak Tracker/StreakCalendar.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#139 Updated Background
  index.css
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024, UI

#144 List the patreon in project.js
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#145 fix logo
  assets/patreon.png
  projects.js
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024, UI

#148 Reaction time tester
  Flashlight-Toggle-App/.gitignore
  Flashlight-Toggle-App/README.md
  Flashlight-Toggle-App/eslint.config.js
  Flashlight-Toggle-App/index.html
  Flashlight-Toggle-App/package-lock.json
  Flashlight-Toggle-App/package.json
  Flashlight-Toggle-App/postcss.config.js
  Flashlight-Toggle-App/public/vite.svg
  Flashlight-Toggle-App/src/App.css
  Flashlight-Toggle-App/src/App.jsx
  Flashlight-Toggle-App/src/assets/react.svg
  Flashlight-Toggle-App/src/components/FlashlightToggle.jsx
  Flashlight-Toggle-App/src/index.css
  Flashlight-Toggle-App/src/main.jsx
  Flashlight-Toggle-App/tailwind.config.js
  Flashlight-Toggle-App/vite.config.js
  Reaction-Time-Tester/Historical-Event-Of-The-Day/.gitignore
  Reaction-Time-Tester/Historical-Event-Of-The-Day/README.md
  Reaction-Time-Tester/Historical-Event-Of-The-Day/eslint.config.js
  Reaction-Time-Tester/Historical-Event-Of-The-Day/index.html
  Reaction-Time-Tester/Historical-Event-Of-The-Day/package-lock.json
  Reaction-Time-Tester/Historical-Event-Of-The-Day/package.json
  Reaction-Time-Tester/Historical-Event-Of-The-Day/postcss.config.js
  Reaction-Time-Tester/Historical-Event-Of-The-Day/public/vite.svg
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/App.css
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/App.jsx
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/assets/react.svg
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/components/HistoricalEvents.jsx
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/index.css
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/main.jsx
  Reaction-Time-Tester/Historical-Event-Of-The-Day/tailwind.config.js
  Reaction-Time-Tester/Historical-Event-Of-The-Day/vite.config.js
  Reaction-Time-Tester/Reaction-Time-Tester/.gitignore
  Reaction-Time-Tester/Reaction-Time-Tester/README.md
  Reaction-Time-Tester/Reaction-Time-Tester/eslint.config.js
  Reaction-Time-Tester/Reaction-Time-Tester/index.html
  Reaction-Time-Tester/Reaction-Time-Tester/package-lock.json
  Reaction-Time-Tester/Reaction-Time-Tester/package.json
  Reaction-Time-Tester/Reaction-Time-Tester/postcss.config.js
  Reaction-Time-Tester/Reaction-Time-Tester/public/vite.svg
  Reaction-Time-Tester/Reaction-Time-Tester/src/App.css
  Reaction-Time-Tester/Reaction-Time-Tester/src/App.jsx
  Reaction-Time-Tester/Reaction-Time-Tester/src/assets/react.svg
  Reaction-Time-Tester/Reaction-Time-Tester/src/components/ReactionTimeTester.jsx
  Reaction-Time-Tester/Reaction-Time-Tester/src/index.css
  Reaction-Time-Tester/Reaction-Time-Tester/src/main.jsx
  Reaction-Time-Tester/Reaction-Time-Tester/tailwind.config.js
  Reaction-Time-Tester/Reaction-Time-Tester/vite.config.js
Labels: hacktoberfest, opensource-contribution, Hacktoberfest2024

#149 Earth 10005
  Flashlight-Toggle-App/.gitignore
  Flashlight-Toggle-App/README.md
  Flashlight-Toggle-App/eslint.config.js
  Flashlight-Toggle-App/index.html
  Flashlight-Toggle-App/package-lock.json
  Flashlight-Toggle-App/package.json
  Flashlight-Toggle-App/postcss.config.js
  Flashlight-Toggle-App/public/vite.svg
  Flashlight-Toggle-App/src/App.css
  Flashlight-Toggle-App/src/App.jsx
  Flashlight-Toggle-App/src/assets/react.svg
  Flashlight-Toggle-App/src/components/FlashlightToggle.jsx
  Flashlight-Toggle-App/src/index.css
  Flashlight-Toggle-App/src/main.jsx
  Flashlight-Toggle-App/tailwind.config.js
  Flashlight-Toggle-App/vite.config.js
  Reaction-Time-Tester/Historical-Event-Of-The-Day/.gitignore
  Reaction-Time-Tester/Historical-Event-Of-The-Day/README.md
  Reaction-Time-Tester/Historical-Event-Of-The-Day/eslint.config.js
  Reaction-Time-Tester/Historical-Event-Of-The-Day/index.html
  Reaction-Time-Tester/Historical-Event-Of-The-Day/package-lock.json
  Reaction-Time-Tester/Historical-Event-Of-The-Day/package.json
  Reaction-Time-Tester/Historical-Event-Of-The-Day/postcss.config.js
  Reaction-Time-Tester/Historical-Event-Of-The-Day/public/vite.svg
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/App.css
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/App.jsx
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/assets/react.svg
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/components/HistoricalEvents.jsx
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/index.css
  Reaction-Time-Tester/Historical-Event-Of-The-Day/src/main.jsx
  Reaction-Time-Tester/Historical-Event-Of-The-Day/tailwind.config.js
  Reaction-Time-Tester/Historical-Event-Of-The-Day/vite.config.js
  Reaction-Time-Tester/Reaction-Time-Tester/.gitignore
  Reaction-Time-Tester/Reaction-Time-Tester/README.md
  Reaction-Time-Tester/Reaction-Time-Tester/eslint.config.js
  Reaction-Time-Tester/Reaction-Time-Tester/index.html
  Reaction-Time-Tester/Reaction-Time-Tester/package-lock.json
  Reaction-Time-Tester/Reaction-Time-Tester/package.json
  Reaction-Time-Tester/Reaction-Time-Tester/postcss.config.js
  Reaction-Time-Tester/Reaction-Time-Tester/public/vite.svg
  Reaction-Time-Tester/Reaction-Time-Tester/src/App.css
  Reaction-Time-Tester/Reaction-Time-Tester/src/App.jsx
  Reaction-Time-Tester/Reaction-Time-Tester/src/assets/react.svg
  Reaction-Time-Tester/Reaction-Time-Tester/src/components/ReactionTimeTester.jsx
  Reaction-Time-Tester/Reaction-Time-Tester/src/index.css
  Reaction-Time-Tester/Reaction-Time-Tester/src/main.jsx
  Reaction-Time-Tester/Reaction-Time-Tester/tailwind.config.js
  Reaction-Time-Tester/Reaction-Time-Tester/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#150 listed flash light toggle
  assets/flashlight.png
  assets/response.png
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#153 listed streak tester
  assets/streak.png
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#156 added personalised greeting generator app
  assets/greeting.png
  personalised-greeting-generator/.gitignore
  personalised-greeting-generator/README.md
  personalised-greeting-generator/eslint.config.js
  personalised-greeting-generator/index.html
  personalised-greeting-generator/package-lock.json
  personalised-greeting-generator/package.json
  personalised-greeting-generator/postcss.config.js
  personalised-greeting-generator/public/vite.svg
  personalised-greeting-generator/src/App.css
  personalised-greeting-generator/src/App.jsx
  personalised-greeting-generator/src/assets/react.svg
  personalised-greeting-generator/src/index.css
  personalised-greeting-generator/src/main.jsx
  personalised-greeting-generator/tailwind.config.js
  personalised-greeting-generator/vite.config.js
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024

#157 mood tracker app
  assets/mood.png
  mood-tracker/.gitignore
  mood-tracker/README.md
  mood-tracker/eslint.config.js
  mood-tracker/index.html
  mood-tracker/package-lock.json
  mood-tracker/package.json
  mood-tracker/postcss.config.js
  mood-tracker/public/vite.svg
  mood-tracker/src/App.css
  mood-tracker/src/App.jsx
  mood-tracker/src/assets/react.svg
  mood-tracker/src/index.css
  mood-tracker/src/main.jsx
  mood-tracker/tailwind.config.js
  mood-tracker/vite.config.js
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, Hacktoberfest2024
