Repository ianshulx/React-projects-for-beginners, pull requests merged in 2025-10, with the labels that each got.

#194 Add Base64 Converter
  base64-converter/.gitignore
  base64-converter/README.md
  base64-converter/eslint.config.js
  base64-converter/index.html
  base64-converter/package-lock.json
  base64-converter/package.json
  base64-converter/public/vite.svg
  base64-converter/src/App.css
  base64-converter/src/App.jsx
  base64-converter/src/assets/react.svg
  base64-converter/src/components/Base64Converter.jsx
  base64-converter/src/index.css
  base64-converter/src/main.jsx
  base64-converter/src/style.css
  base64-converter/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#197 Add Mood Journal App
  Mood-Journal/.gitignore
  Mood-Journal/LICENSE
  Mood-Journal/README.md
  Mood-Journal/assets/Mood-Journal.png
  Mood-Journal/eslint.config.js
  Mood-Journal/index.html
  Mood-Journal/package-lock.json
  Mood-Journal/package.json
  Mood-Journal/public/logo.png
  Mood-Journal/src/App.jsx
  Mood-Journal/src/components/Animation.jsx
  Mood-Journal/src/components/MessageDisplay.jsx
  Mood-Journal/src/components/MoodSelector.jsx
  Mood-Journal/src/index.css
  Mood-Journal/src/main.jsx
  Mood-Journal/vite.config.js
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, hacktoberfest2025

#205 Add Greenleaf Houseplant Store contribution to projects.js
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#207 Retro Desktop Simulator - Windows 95 style React app
  Retro-Desktop-Simulator/.gitignore
  Retro-Desktop-Simulator/README.md
  Retro-Desktop-Simulator/index.html
  Retro-Desktop-Simulator/package-lock.json
  Retro-Desktop-Simulator/package.json
  Retro-Desktop-Simulator/src/App.css
  Retro-Desktop-Simulator/src/App.jsx
  Retro-Desktop-Simulator/src/components/Desktop.css
  Retro-Desktop-Simulator/src/components/Desktop.jsx
  Retro-Desktop-Simulator/src/components/StartMenu.css
  Retro-Desktop-Simulator/src/components/StartMenu.jsx
  Retro-Desktop-Simulator/src/components/Taskbar.css
  Retro-Desktop-Simulator/src/components/Taskbar.jsx
  Retro-Desktop-Simulator/src/components/Window.css
  Retro-Desktop-Simulator/src/components/Window.jsx
  Retro-Desktop-Simulator/src/components/apps/Calculator.css
  Retro-Desktop-Simulator/src/components/apps/Calculator.jsx
  Retro-Desktop-Simulator/src/components/apps/Notepad.css
  Retro-Desktop-Simulator/src/components/apps/Notepad.jsx
  Retro-Desktop-Simulator/src/components/apps/Paint.css
  Retro-Desktop-Simulator/src/components/apps/Paint.jsx
  Retro-Desktop-Simulator/src/index.css
  Retro-Desktop-Simulator/src/main.jsx
  Retro-Desktop-Simulator/vite.config.js
  assets/retro-desktop.svg
  projects.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, hacktoberfest2025

#208 Developed Video Calling App using ZeoCLoud
  assets/video-calling-app.png
  projects.js
  video_calling_app/.gitignore
  video_calling_app/README.md
  video_calling_app/eslint.config.js
  video_calling_app/index.html
  video_calling_app/package-lock.json
  video_calling_app/package.json
  video_calling_app/postcss.config.cjs
  video_calling_app/public/vite.svg
  video_calling_app/src/App.jsx
  video_calling_app/src/assets/react.svg
  video_calling_app/src/assets/video-calling-app.png
  video_calling_app/src/components/Faq.jsx
  video_calling_app/src/components/Footer.jsx
  video_calling_app/src/components/Hero.jsx
  video_calling_app/src/components/HeroTemp.jsx
  video_calling_app/src/components/Home.jsx
  video_calling_app/src/components/Navbar.jsx
  video_calling_app/src/components/PartnerLogo.jsx
  video_calling_app/src/components/Testimonial.jsx
  video_calling_app/src/components/VideoComp.jsx
  video_calling_app/src/index.css
  video_calling_app/src/index.js
  video_calling_app/src/main.jsx
  video_calling_app/tailwind.config.js
  video_calling_app/vite.config.js
Labels: hacktoberfest, opensource-contribution, hacktoberfest2025

#210 Improved the Header / Navbar🚀
  TODO.md
  hamburger-menu.js
  index.css
  index.html
  menu-toggle.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, opensource-contribution, UI, hacktoberfest2025

#214 Update BMICalculator.jsx
  BMI-Calculator/src/components/BMICalculator.jsx
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, hacktoberfest2025

#215 Added flashcards and quizzes
  Gemini-powered-flashcards/my-app/.gitignore
  Gemini-powered-flashcards/my-app/README.md
  Gemini-powered-flashcards/my-app/app/animation.html
  Gemini-powered-flashcards/my-app/app/favicon.ico
  Gemini-powered-flashcards/my-app/app/globals.css
  Gemini-powered-flashcards/my-app/app/layout.tsx
  Gemini-powered-flashcards/my-app/app/page.tsx
  Gemini-powered-flashcards/my-app/eslint.config.mjs
  Gemini-powered-flashcards/my-app/next.config.ts
  Gemini-powered-flashcards/my-app/package-lock.json
  Gemini-powered-flashcards/my-app/package.json
  Gemini-powered-flashcards/my-app/postcss.config.mjs
  Gemini-powered-flashcards/my-app/public/file.svg
  Gemini-powered-flashcards/my-app/public/globe.svg
  Gemini-powered-flashcards/my-app/public/next.svg
  Gemini-powered-flashcards/my-app/public/vercel.svg
  Gemini-powered-flashcards/my-app/public/window.svg
  Gemini-powered-flashcards/my-app/tsconfig.json
  my-app/.gitignore
  my-app/README.md
  my-app/app/_page.tsx
  my-app/app/_page1.tsx
  my-app/app/animation.html
  my-app/app/favicon.ico
  my-app/app/globals.css
  my-app/app/layout.tsx
  my-app/app/page.tsx
  my-app/eslint.config.mjs
  my-app/next.config.ts
  my-app/package-lock.json
  my-app/package.json
  my-app/postcss.config.mjs
  my-app/tsconfig.json
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, hacktoberfest2025

#219 Added random-advice-generator using react.
  Random-Advice-Generator/.gitignore
  Random-Advice-Generator/README.md
  Random-Advice-Generator/eslint.config.js
  Random-Advice-Generator/index.html
  Random-Advice-Generator/package-lock.json
  Random-Advice-Generator/package.json
  Random-Advice-Generator/public/vite.svg
  Random-Advice-Generator/src/Advice.css
  Random-Advice-Generator/src/Advice.jsx
  Random-Advice-Generator/src/App.css
  Random-Advice-Generator/src/App.jsx
  Random-Advice-Generator/src/images/icon-dice.svg
  Random-Advice-Generator/src/images/pattern-divider-desktop.svg
  Random-Advice-Generator/src/images/pattern-divider-mobile.svg
  Random-Advice-Generator/src/index.css
  Random-Advice-Generator/src/main.jsx
  Random-Advice-Generator/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, hacktoberfest2025

#228 added projects list
  assets/#meme.jpeg
  assets/advice.jpeg
  assets/cart.jpeg
  assets/doc.webp
  assets/elrn.jpeg
  assets/houseplant.jpeg
  assets/mood.jpeg
  assets/puzz.jpeg
  assets/win95.jpeg
  projects.js
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, opensource-contribution, new-project, hacktoberfest2025

#231 added few more icons
  assets/meme.jpeg
  assets/vidcall.png
  projects.js
Labels: documentation, hacktoberfest, hacktoberfest-accepted, opensource-contribution, UI, hacktoberfest2025

#244 pokimon generator project added
  random-pokimon-generator/.gitignore
  random-pokimon-generator/README.md
  random-pokimon-generator/eslint.config.js
  random-pokimon-generator/index.html
  random-pokimon-generator/package-lock.json
  random-pokimon-generator/package.json
  random-pokimon-generator/public/vite.svg
  random-pokimon-generator/src/App.css
  random-pokimon-generator/src/App.jsx
  random-pokimon-generator/src/assets/react.svg
  random-pokimon-generator/src/index.css
  random-pokimon-generator/src/main.jsx
  random-pokimon-generator/src/pokimanGenrator.jsx
  random-pokimon-generator/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, hacktoberfest2025

#245 listed 6 new contro projects
  assets/blinkit.png
  assets/google.png
  assets/magic.png
  assets/poke.png
  assets/souled.png
  assets/tetris.png
  projects.js
Labels: documentation, enhancement, invalid, hacktoberfest, hacktoberfest-accepted, opensource-contribution, new-project, hacktoberfest2025

#246 fixed little error
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, opensource-contribution, UI, hacktoberfest2025

#250 added netflex home page clone
  netflix-clone/.gitignore
  netflix-clone/README.md
  netflix-clone/eslint.config.js
  netflix-clone/index.html
  netflix-clone/package-lock.json
  netflix-clone/package.json
  netflix-clone/public/vite.svg
  netflix-clone/src/App.css
  netflix-clone/src/App.jsx
  netflix-clone/src/assets/react.svg
  netflix-clone/src/index.css
  netflix-clone/src/main.jsx
  netflix-clone/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2025

#252 zomato clone project added
  zomato-clone/.gitignore
  zomato-clone/README.md
  zomato-clone/eslint.config.js
  zomato-clone/index.html
  zomato-clone/package-lock.json
  zomato-clone/package.json
  zomato-clone/public/vite.svg
  zomato-clone/src/App.css
  zomato-clone/src/App.jsx
  zomato-clone/src/assets/react.svg
  zomato-clone/src/index.css
  zomato-clone/src/main.jsx
  zomato-clone/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted, opensource-contribution, hacktoberfest2025

#253 removed unnecessary files
  .github/workflows/deploy.yml
  .github/workflows/github-pages.yml
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2025
